// scripts/extract-hardcoded-data.ts
// Extract all hardcoded data from travel-info page with proper Cloudinary URLs

import { LinkData } from './migrate-links-to-sanity'

export const CATEGORY_MAPPING = {
  'resortsData': 'Resorts',
  'airlinesData': 'Airlines', 
  'trainsData': 'Trains',
  'chaletAccommodationData': 'Chalet accommodation',
  'selfCateredAccommodationData': 'Self-catered Accommodation',
  'weatherData': 'Weather',
  'skiSchoolsData': 'Ski Schools',
  'skiHireData': 'Ski hire',
  'achesAndPainsData': 'Aches and pains',
  'lifeInResortData': 'Life in resort info',
  'informationWebsitesData': 'Information Websites',
  'selfCateringData': 'Self catering',
}

// Full dataset with Cloudinary URLs and proper formats
export const FULL_MIGRATION_DATA = {
  resortsData: [
    {
      id: 'val-thorens',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754926825/logos/valthorens.svg',
      companyName: 'Val Thorens',
      url: 'https://www.valthorens.com/',
      description: 'At 2,300m altitude, Val Thorens is Europe\'s highest ski resort with guaranteed snow from November to May. Part of the world\'s largest ski area, it offers 600km of slopes and stunning panoramic views of the French Alps.',
    },
    {
      id: 'courchevel',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754926821/logos/courchevel.svg',
      companyName: 'Courchevel',
      url: 'https://www.courchevel.com/',
      description: 'Courchevel is synonymous with luxury skiing. Famous for its pristine pistes, world-class dining, and exclusive boutiques, it\'s where royalty and celebrities come to ski. The resort offers skiing for all levels across four villages.',
    },
    {
      id: 'meribel',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754926824/logos/meribel.svg',
      companyName: 'Méribel',
      url: 'https://www.meribel.net/',
      description: 'Méribel offers authentic alpine charm in the heart of the Three Valleys. Known for its traditional chalet architecture and excellent ski schools, it\'s perfect for families and intermediate skiers.',
    },
    {
      id: 'les-menuires',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754926823/logos/menuires.svg',
      companyName: 'Les Menuires',
      url: 'https://www.lesmenuires.com/',
      description: 'Les Menuires provides excellent value skiing with direct access to the Three Valleys. Modern apartments and reliable snow conditions make it popular with budget-conscious families.',
    },
    {
      id: 'saint-martin-de-belleville',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754926826/logos/stmartin.svg',
      companyName: 'Saint Martin de Belleville',
      url: 'https://www.saintmartindebelleville.com/',
      description: 'A charming traditional Savoyard village offering authentic mountain culture and direct access to the Three Valleys ski area.',
    },
    {
      id: 'la-tania',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754926827/logos/la-tania.svg',
      companyName: 'La Tania',
      url: 'https://www.latania.com/',
      description: 'Built for the 1992 Olympics, La Tania is a purpose-built resort offering modern amenities and easy access to Courchevel and Méribel slopes.',
    },
  ] as LinkData[],

  trainsData: [
    {
      id: 'eurostar',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754930143/logos/eurostar.svg',
      companyName: 'Eurostar',
      url: 'https://www.eurostar.com/',
      description: 'Direct overnight service from London to Moutiers every Saturday during ski season. Arrive refreshed and avoid airport queues.',
    },
    {
      id: 'rail-europe',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755075998/logos/rail-europe.svg',
      companyName: 'Rail Europe',
      url: 'https://www.raileurope.com/',
      description: 'Book train tickets for travel across Europe. Convenient connections to major ski destinations in the Alps.',
    },
    {
      id: 'rtm',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754927308/logos/rtm.svg',
      companyName: 'RTM',
      url: 'https://cdn.worldvectorlogo.com/logos/rtm.svg',
      description: 'Regional transport operator (logo provided for completeness).',
    },
    {
      id: 'trainline',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754930155/logos/trainline.svg',
      companyName: 'Trainline',
      url: 'https://www.thetrainline.com/',
      description: 'Plan and book European train journeys in one place.',
    },
  ] as LinkData[],

  chaletAccommodationData: [
    {
      id: 'oxford-ski',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755008602/logos/oxford-ski.svg',
      companyName: 'Oxford Ski',
      url: 'https://www.oxfordski.com/',
      description: 'Tailor-made luxury ski holidays and chalets across premier Alpine resorts.',
    },
    {
      id: 'meriski',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756306241/logos/meriski.svg',
      companyName: 'Meriski',
      url: 'https://www.meriski.com/',
      description: 'Luxury chalet holidays in Méribel with exceptional service and attention to detail.',
    },
    {
      id: 'alpine-escape',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755008604/logos/alpine-escape.png',
      companyName: 'Alpine Escape',
      url: 'https://www.alpine-escape.co.uk/',
      description: 'Beautiful catered chalets with exceptional service in Courchevel and La Tania.',
    },
    {
      id: 'fish-and-pips',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755008605/logos/fish-and-pips.svg',
      companyName: 'Fish & Pips',
      url: 'https://www.fandptravel.com/',
      description: 'Handpicked luxury chalets and hotels with a passion for food and service.',
    },
    {
      id: 'ski-cuisine',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756300548/logos/ski-cuisine.svg',
      companyName: 'Ski Cuisine',
      url: 'https://www.skicuisine.com/',
      description: 'Gourmet ski holidays combining exceptional skiing with world-class dining experiences.',
    },
    {
      id: 'elegant-resorts',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754930152/logos/elegant-resorts.svg',
      companyName: 'Elegant Resorts',
      url: 'https://www.elegantresorts.co.uk/',
      description: 'Luxury travel company offering tailor-made ski holidays.',
    },
    {
      id: 'meribel-ski-chalets',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755008607/logos/meribel-ski-chalets.webp',
      companyName: 'Méribel Ski Chalet',
      url: 'https://www.meribel-chalets.co.uk/',
      description: 'Independent specialist with a range of catered and self-catered chalets in Méribel.',
    },
    {
      id: 'com-ski',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755528558/logos/com-ski.svg',
      companyName: 'com-ski.com',
      url: 'https://www.com-ski.com/',
      description: 'Comprehensive ski holiday booking platform with a wide selection of chalets and resorts.',
    },
    {
      id: 'leski',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755076000/logos/leski.svg',
      companyName: 'Le Ski',
      url: 'https://www.leski.com/',
      description: 'British ski company offering catered chalets and quality ski instruction in the French Alps.',
    },
    {
      id: 'alpine-answers',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754930148/logos/alpine-answers.svg',
      companyName: 'Alpine Answers',
      url: 'https://www.alpineanswers.co.uk/',
      description: 'Specialist ski holiday agency with extensive resort knowledge.',
    },
    {
      id: 'ski-blanc',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756224924/logos/ski-blanc.png',
      companyName: 'Ski Blanc',
      url: 'https://www.skiblanc.co.uk/',
      description: 'Luxury ski holidays with a focus on exceptional service and beautiful chalets.',
    },
    {
      id: 'ski-basics',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754930150/logos/ski-basics.svg',
      companyName: 'Ski Basics',
      url: 'https://www.skibasics.com/',
      description: 'Quality catered chalets and services in Méribel.',
    },
    {
      id: 'delicious-mountain',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756301700/logos/delicious-mountain.svg',
      companyName: 'Delicious Mountain',
      url: 'https://www.deliciousmountain.com/',
      description: 'Food-focused ski holidays with gourmet dining and exceptional chalet experiences.',
    },
    {
      id: 'alpine-ethos',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755528563/logos/alpine-ethos.svg',
      companyName: 'Alpine Ethos',
      url: 'https://www.alpineethos.com/',
      description: 'Boutique ski holiday specialist offering unique and authentic Alpine experiences.',
    },
    {
      id: 'skivo',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756225114/logos/skivo.png',
      companyName: 'Skivo',
      url: 'https://www.skivo.co.uk/',
      description: 'Independent ski holiday specialist with a personal touch and extensive resort knowledge.',
    },
    {
      id: 'firefly',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755534748/logos/firefly.svg',
      companyName: 'Firefly',
      url: 'https://www.fireflyski.com/',
      description: 'Luxury ski holidays with a focus on exceptional service and beautiful properties.',
    },
    {
      id: 'alpine-independence',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755528569/logos/alpine-independence.svg',
      companyName: 'Alpine Independence',
      url: 'https://www.alpineindependence.com/',
      description: 'Independent ski holiday specialist offering personalized service and expert advice.',
    },
  ] as LinkData[],

  selfCateredAccommodationData: [
    {
      id: 'courchevel-rentals',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756225344/logos/courchevel-chalets.svg',
      companyName: 'Courchevel Chalet and Apartment Rentals',
      url: 'https://www.courchevelchaletrentals.com/',
      description: 'Extensive portfolio of luxury chalets and apartments throughout all Courchevel villages. From intimate retreats to large group properties.',
    },
    {
      id: 'meribel-rentals',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756225380/logos/meribel-chalets.svg',
      companyName: 'Meribel Chalet and Apartment Rentals',
      url: 'https://www.meribelchaletrentals.com/',
      description: 'Authentic alpine properties in Méribel village and surrounding areas. Traditional chalets with modern amenities.',
    },
    {
      id: 'ams-rentals',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756306041/logos/ams.svg',
      companyName: 'AMS Rentals',
      url: 'https://www.amsrentals.com/',
      description: 'Exclusive Méribel Valley specialist offering premium self-catered properties. Weekly and seasonal rentals available.',
    },
    {
      id: 'ski-lettings',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755528572/logos/ski-lettings.svg',
      companyName: 'Ski Lettings',
      url: 'https://www.skilettings.com/',
      description: 'Specialist in self-catered ski accommodation across the French Alps with a focus on quality and value.',
    },
    {
      id: 'sno-mobi',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756224656/logos/sno-mobi.png',
      companyName: 'Sno.mobi',
      url: 'https://www.sno.mobi/',
      description: 'Innovative platform for finding and booking self-catered ski accommodation with real-time availability.',
    },
  ] as LinkData[],

  weatherData: [
    {
      id: 'meteo-france',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755075996/logos/meteo-france.svg',
      companyName: 'Météo France',
      url: 'https://meteofrance.com/meteo-montagne/alpes-du-nord',
      description: 'Official French weather service with detailed mountain forecasts, avalanche bulletins, and snow reports.',
    },
    {
      id: 'snow-forecast',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754930154/logos/snow-forecast.svg',
      companyName: 'Snow Forecast',
      url: 'https://www.snow-forecast.com/',
      description: 'Reliable snow forecasts and ski conditions for resorts worldwide.',
    },
  ] as LinkData[],

  skiSchoolsData: [
    {
      id: 'esf',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756306234/logos/esf.svg',
      companyName: 'ESF (École du Ski Français)',
      url: 'https://www.esf.net/',
      description: 'France\'s largest ski school network with qualified instructors in every resort. Group and private lessons for all levels.',
    },
    {
      id: 'new-generation',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755532004/logos/new-generation.svg',
      companyName: 'New Generation Ski School',
      url: 'https://www.skinewgen.com/',
      description: 'British-run ski school offering English instruction in major Three Valleys resorts. Small groups and performance-focused teaching.',
    },
    {
      id: 'supreme-ski',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754927311/logos/supreme.svg',
      companyName: 'Supreme Ski & Snowboard School',
      url: 'https://www.supremeski.com/',
      description: 'Established British ski school operating across top French resorts, offering private and group lessons with experienced instructors.',
    },
    {
      id: 'snow-limits',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756225622/logos/snow-limits.png',
      companyName: 'Snow Limits',
      url: 'https://www.snowlimits.com/',
      description: 'Specialist ski school focusing on advanced techniques and off-piste skiing for experienced skiers.',
    },
    {
      id: 'rtm-snowboarding',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755528577/logos/rtm-snowboarding.svg',
      companyName: 'RTM Snowboarding',
      url: 'https://www.rtmsnowboarding.com/',
      description: 'Dedicated snowboard school with expert instructors specializing in freestyle and freeride techniques.',
    },
    {
      id: 'oxygene',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756225803/logos/oxygene.png',
      companyName: 'Oxygene',
      url: 'https://www.oxygene.ski/',
      description: 'International ski school with English-speaking instructors offering lessons in multiple languages.',
    },
    {
      id: 'momentum',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756225916/logos/momentum.png',
      companyName: 'Momentum',
      url: 'https://www.momentumski.com/',
      description: 'Performance-focused ski school specializing in advanced techniques and competition preparation.',
    },
    {
      id: 'marmalade',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756300789/logos/marmalade.svg',
      companyName: 'Marmalade',
      url: 'https://www.marmaladeski.com/',
      description: 'Boutique ski school offering personalized instruction and small group lessons in a friendly atmosphere.',
    },
  ] as LinkData[],

  skiHireData: [
    {
      id: 'white-storm',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756306244/logos/whitestorm.svg',
      companyName: 'White Storm',
      url: 'https://www.whitestorm.com/',
      description: 'Whitestorm have ski rental shops in Courchevel (1850), Courchevel Moriond (1650) and Le Praz with mobile delivery in Courchevel Village (1550). There\'s a massive 35% off if using the promo code "3VT" on their site and during the quiet times of the season, this may increase to 50%... so what are you waiting for...?!',
    },
    {
      id: 'ski-higher',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756306238/logos/skihigher.svg',
      companyName: 'Ski Higher',
      url: 'https://www.skihigher.com/',
      description: 'Ski Higher provide quality rental equipment at very reasonable prices. The even better news is that we have secured a massive 20% discount if you book online through their new website! They have shops in Courchevel 1850, Le Praz, La Tania, Meribel and Les Allues.',
    },
    {
      id: 'freeride-france',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756301567/logos/freeride-france.svg',
      companyName: 'Freeride France',
      url: 'https://www.freeridefrance.com/',
      description: 'Specialist freeride equipment rental with high-performance gear for off-piste adventures and backcountry skiing.',
    },
    {
      id: 'slide-candy',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756301659/logos/slide-candy.png',
      companyName: 'Slide Candy',
      url: 'https://www.slidecandy.com/',
      description: 'Premium ski and snowboard rental with the latest equipment and personalized fitting service.',
    },
  ] as LinkData[],

  achesAndPainsData: [
    {
      id: 'ski-physio',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754927310/logos/ski-physio.svg',
      companyName: 'Ski-Physio',
      url: 'https://www.ski-physio.com/',
      description: 'Physiotherapy services specializing in ski-related injuries and recovery in the Alps.',
    },
  ] as LinkData[],

  lifeInResortData: [
    {
      id: 'trois-vallees-guide',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1754927312/logos/trois-vallees-guide.svg',
      companyName: 'Three Valleys Resort Guide',
      url: 'https://www.les3vallees.com/',
      description: 'Official Three Valleys guide with events, restaurant recommendations, and insider tips for mountain life.',
    },
  ] as LinkData[],

  informationWebsitesData: [
    {
      id: 'meribel-unplugged',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755528588/logos/meribel-unplugged.svg',
      companyName: 'Meribel Unplugged',
      url: 'https://www.meribelunplugged.com/',
      description: 'Comprehensive guide to Méribel with insider tips, restaurant reviews, and local knowledge.',
    },
    {
      id: 'thesnowco',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755528595/logos/thesnowco.svg',
      companyName: 'Thesnowco',
      url: 'https://www.thesnowco.com/',
      description: 'Expert ski holiday advice and resort information from experienced ski professionals.',
    },
    {
      id: 'merinet',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755528594/logos/merinet.svg',
      companyName: 'Merinet',
      url: 'https://www.merinet.com/',
      description: 'Local Méribel information portal with weather updates, snow reports, and resort news.',
    },
    {
      id: 'welove2ski',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755528596/logos/welove2ski.svg',
      companyName: 'Welove2ski',
      url: 'https://www.welove2ski.com/',
      description: 'Passionate ski community sharing resort reviews, ski tips, and holiday planning advice.',
    },
    {
      id: 'courchnet',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756300591/logos/courchnet.svg',
      companyName: 'Courchnet',
      url: 'https://www.courchnet.com/',
      description: 'Dedicated Courchevel information site with resort guides, weather updates, and local insights.',
    },
    {
      id: 'snowheads',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756300047/logos/snowheads.gif',
      companyName: 'Snowheads',
      url: 'https://www.snowheads.co.uk/',
      description: 'UK\'s largest ski community forum with expert advice, trip reports, and ski holiday planning.',
    },
    {
      id: 'natives',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756299531/logos/natives.png',
      companyName: 'Natives.co.uk',
      url: 'https://www.natives.co.uk/',
      description: 'Comprehensive ski resort guides with detailed information, photos, and user reviews.',
    },
    {
      id: 'unplugged-courchevel',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1755528597/logos/unplugged-courchevel.svg',
      companyName: 'Unplugged Courchevel',
      url: 'https://www.unpluggedcourchevel.com/',
      description: 'Insider\'s guide to Courchevel with restaurant recommendations, events, and local knowledge.',
    },
  ] as LinkData[],

  selfCateringData: [
    {
      id: 'extreme-cuisine',
      logo: 'https://res.cloudinary.com/dzrn3khsd/image/upload/v1756298209/logos/extreme-cuisine.jpg',
      companyName: 'Extreme Cuisine',
      url: 'https://www.extremecuisine.com/',
      description: 'Gourmet food delivery service offering premium ingredients, prepared meals, and specialty items for your ski holiday.',
    },
  ] as LinkData[],
}